sudo: false

dist: xenial

language: node_js
node_js:
  - "10"

env:
  - BROWSER=ChromeCi
  - BROWSER=Firefox

cache:
  directories:
    - ~/.yarn-cache
    - node_modules
    - www/node_modules

install:
  - yarn bootstrap

after_success:
  - node_modules/.bin/codecov

branches:
  only:
    - master
    - next
